# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-06 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dummy_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtordinal', models.DecimalField(decimal_places=15, max_digits=25)),
                ('lat', models.DecimalField(decimal_places=17, max_digits=20)),
                ('lng', models.DecimalField(decimal_places=17, max_digits=20)),
                ('mlabel', models.CharField(max_length=100)),
            ],
        ),
    ]
